Update README.md
platformsh/ddev-platformsh pull request #62
Opened 2022-11-15 19:46 UTC by gilzow

Per slack conversation, updates README to include usage instructions for platform.sh projects

2022-11-15 20:00 UTC, rfay commented
Thank you!

2022-11-16 09:02 UTC, lolautruche requested changes

2022-11-16 09:02 UTC, lolautruche commented on README.md
> +7. Run `ddev pull platform` to retrieve a copy of the database and contents from the project's file mounts from the environment you entered in step #5
```suggestion
7. (Optional) Run `ddev pull platform` to retrieve a copy of the database and contents from the project's file mounts from the environment you entered in step #5
```

2022-11-16 09:02 UTC, lolautruche commented on README.md
> +    * A working `ddev pull platform` integration with all mounts is created.
We should mention that we support configured services, and which ones are supported.

2022-12-02 09:50 UTC, lolautruche approved these changes

2022-12-02 09:51 UTC, lolautruche commented
Should be fine now.
Can we merge @rfay ?

2022-12-02 13:44 UTC, rfay approved these changes

2022-12-02 13:44 UTC, merged

2022-12-02 13:45 UTC, rfay commented
Thanks!